
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: mydatabase

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"

    db_migration:
        build: .
        command: python3 manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - db