# Generated by Django 5.1.3 on 2024-11-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_imageupload_uploadfiles_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
