# Generated by Django 5.1.3 on 2024-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_delete_imageupload_delete_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='project_image'),
        ),
    ]
