# Generated by Django 5.1.3 on 2024-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend',
            field=models.CharField(default='', max_length=200),
        ),
    ]
