# Generated by Django 5.1.3 on 2025-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_alter_project_github_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
