# Generated by Django 5.1.3 on 2025-01-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='link_to_live_demo',
        ),
    ]
