# Generated by Django 5.1.3 on 2025-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_rename_link_project_link_to_live_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='database',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='frontend',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
