name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install python-dotenv
        pip install django-cors-headers
        pip install Pillow

    - name: Run tests
      run: |
        python manage.py test
